"""
默认模型配置数据

管理员初始化时导入的默认供应商和模型配置。
这些配置不包含 api_key，由用户自行配置。
"""

from typing import List, Dict, Any


# ==================== 默认供应商配置 ====================

DEFAULT_PROVIDERS: List[Dict[str, Any]] = [
    {
        "name": "openai",
        "label": "OpenAI",
        "description": "OpenAI 提供的 GPT 系列模型，包括 GPT-4o 和 GPT-4o-mini 等。",
        "icon": None,  # 可后续通过管理后台上传
        "icon_background": "#10A37F",
        "default_base_url": "https://api.openai.com/v1",
        "supported_model_types": ["chat"],
        "help_url": "https://platform.openai.com/api-keys",
        "is_builtin": True,
        "position": 1,
    },
    {
        "name": "deepseek",
        "label": "DeepSeek",
        "description": "DeepSeek 深度求索提供的模型，包括 DeepSeek-V3 和 DeepSeek-R1 等。",
        "icon": None,
        "icon_background": "#4D6BFE",
        "default_base_url": "https://api.deepseek.com",
        "supported_model_types": ["chat"],
        "help_url": "https://platform.deepseek.com/api_keys",
        "is_builtin": True,
        "position": 2,
    },
    {
        "name": "tongyi",
        "label": "通义千问",
        "description": "阿里云通义千问系列模型，包括 Qwen-Max、Qwen-Plus 等。",
        "icon": None,
        "icon_background": "#6366F1",
        "default_base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "supported_model_types": ["chat"],
        "help_url": "https://dashscope.console.aliyun.com/apiKey",
        "is_builtin": True,
        "position": 3,
    },
    {
        "name": "moonshot",
        "label": "月之暗面",
        "description": "Moonshot AI 月之暗面提供的 Kimi 系列模型。",
        "icon": None,
        "icon_background": "#000000",
        "default_base_url": "https://api.moonshot.cn/v1",
        "supported_model_types": ["chat"],
        "help_url": "https://platform.moonshot.cn/console/api-keys",
        "is_builtin": True,
        "position": 4,
    },
    {
        "name": "ollama",
        "label": "Ollama",
        "description": "本地部署的 Ollama 模型服务，支持多种开源模型。",
        "icon": None,
        "icon_background": "#FFFFFF",
        "default_base_url": "http://localhost:11434",
        "supported_model_types": ["chat"],
        "help_url": "https://ollama.ai/",
        "is_builtin": True,
        "position": 5,
    },
]


# ==================== 默认模型配置 ====================

DEFAULT_MODELS: List[Dict[str, Any]] = [
    # ==================== OpenAI ====================
    {
        "provider_name": "openai",
        "model_name": "gpt-4o",
        "label": "GPT-4o",
        "description": "OpenAI 最强大的多模态模型，支持图像输入和工具调用。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought", "image_input"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "default_temperature": 0.7,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "gpt-4o"},
        "pricing": {"input": 0.0183, "output": 0.0733, "unit": 0.001, "currency": "RMB"},
        "position": 1,
    },
    {
        "provider_name": "openai",
        "model_name": "gpt-4o-mini",
        "label": "GPT-4o Mini",
        "description": "GPT-4o 的轻量版本，性价比高，适合大多数场景。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought", "image_input"],
        "context_window": 128000,
        "max_output_tokens": 16384,
        "default_temperature": 0.7,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "gpt-4o-mini"},
        "pricing": {"input": 0.00105, "output": 0.0042, "unit": 0.001, "currency": "RMB"},
        "position": 2,
    },

    # ==================== DeepSeek ====================
    {
        "provider_name": "deepseek",
        "model_name": "deepseek-chat",
        "label": "DeepSeek-V3",
        "description": "DeepSeek 最新一代对话模型，性能优秀，价格实惠。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought"],
        "context_window": 64000,
        "max_output_tokens": 8000,
        "default_temperature": 0.7,
        "default_top_p": 1.0,
        "default_max_tokens": 4000,
        "attributes": {"model": "deepseek-chat"},
        "pricing": {"input": 0.002, "output": 0.008, "unit": 0.001, "currency": "RMB"},
        "position": 1,
    },
    {
        "provider_name": "deepseek",
        "model_name": "deepseek-reasoner",
        "label": "DeepSeek-R1",
        "description": "DeepSeek 推理模型，支持深度思考，适合复杂推理任务。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought", "thinking"],
        "context_window": 64000,
        "max_output_tokens": 8000,
        "default_temperature": 0.7,
        "default_top_p": 1.0,
        "default_max_tokens": 4000,
        "attributes": {"model": "deepseek-reasoner"},
        "pricing": {"input": 0.004, "output": 0.016, "unit": 0.001, "currency": "RMB"},
        "position": 2,
    },

    # ==================== 通义千问 ====================
    {
        "provider_name": "tongyi",
        "model_name": "qwen-plus",
        "label": "通义千问 Plus",
        "description": "通义千问增强版，平衡性能与成本。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought"],
        "context_window": 131072,
        "max_output_tokens": 8192,
        "default_temperature": 0.7,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "qwen-plus"},
        "pricing": {"input": 0.0008, "output": 0.002, "unit": 0.001, "currency": "RMB"},
        "position": 1,
    },
    {
        "provider_name": "tongyi",
        "model_name": "qwen-max",
        "label": "通义千问 Max",
        "description": "通义千问旗舰版，适合复杂任务。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought"],
        "context_window": 32768,
        "max_output_tokens": 8192,
        "default_temperature": 0.7,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "qwen-max"},
        "pricing": {"input": 0.02, "output": 0.06, "unit": 0.001, "currency": "RMB"},
        "position": 2,
    },
    {
        "provider_name": "tongyi",
        "model_name": "qwen3-max",
        "label": "通义千问3 Max",
        "description": "通义千问第三代旗舰模型，支持深度思考。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought", "thinking"],
        "context_window": 32768,
        "max_output_tokens": 8192,
        "default_temperature": 0.7,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "qwen3-max"},
        "pricing": {"input": 0.02, "output": 0.06, "unit": 0.001, "currency": "RMB"},
        "position": 3,
    },
    {
        "provider_name": "tongyi",
        "model_name": "qwen-vl-plus",
        "label": "通义千问 VL Plus",
        "description": "通义千问多模态模型，支持图像理解。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought", "image_input"],
        "context_window": 131072,
        "max_output_tokens": 8192,
        "default_temperature": 0.7,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "qwen-vl-plus"},
        "pricing": {"input": 0.003, "output": 0.006, "unit": 0.001, "currency": "RMB"},
        "position": 4,
    },

    # ==================== 月之暗面 ====================
    {
        "provider_name": "moonshot",
        "model_name": "moonshot-v1-8k",
        "label": "Moonshot V1 8K",
        "description": "月之暗面 8K 上下文模型，适合短对话。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought"],
        "context_window": 8192,
        "max_output_tokens": 8192,
        "default_temperature": 0.85,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "moonshot-v1-8k"},
        "pricing": {"input": 0.012, "output": 0.012, "unit": 0.001, "currency": "RMB"},
        "position": 1,
    },
    {
        "provider_name": "moonshot",
        "model_name": "moonshot-v1-32k",
        "label": "Moonshot V1 32K",
        "description": "月之暗面 32K 上下文模型，适合中等长度对话。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought"],
        "context_window": 32768,
        "max_output_tokens": 32768,
        "default_temperature": 0.85,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "moonshot-v1-32k"},
        "pricing": {"input": 0.024, "output": 0.024, "unit": 0.001, "currency": "RMB"},
        "position": 2,
    },
    {
        "provider_name": "moonshot",
        "model_name": "moonshot-v1-128k",
        "label": "Moonshot V1 128K",
        "description": "月之暗面 128K 超长上下文模型，支持图像输入。",
        "model_type": "chat",
        "features": ["tool_call", "agent_thought", "image_input"],
        "context_window": 131072,
        "max_output_tokens": 131072,
        "default_temperature": 0.85,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "moonshot-v1-128k"},
        "pricing": {"input": 0.06, "output": 0.06, "unit": 0.001, "currency": "RMB"},
        "position": 3,
    },

    # ==================== Ollama ====================
    {
        "provider_name": "ollama",
        "model_name": "qwen2.5:7b",
        "label": "Qwen2.5 7B",
        "description": "本地部署的 Qwen2.5 7B 模型。",
        "model_type": "chat",
        "features": ["tool_call"],
        "context_window": 32768,
        "max_output_tokens": 8192,
        "default_temperature": 0.7,
        "default_top_p": 1.0,
        "default_max_tokens": 4096,
        "attributes": {"model": "qwen2.5:7b"},
        "pricing": None,
        "position": 1,
    },
]


# ==================== 默认参数模板（用于前端展示） ====================

DEFAULT_PARAMETER_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "temperature": {
        "label": "温度",
        "type": "float",
        "help": "温度控制随机性。较低的值使模型更加确定性，较高的值则更加随机。",
        "default": 0.7,
        "min": 0,
        "max": 2,
        "step": 0.1,
    },
    "top_p": {
        "label": "Top P",
        "type": "float",
        "help": "通过核心采样控制多样性。0.1表示只考虑概率最高的10%的token。",
        "default": 1.0,
        "min": 0,
        "max": 1,
        "step": 0.1,
    },
    "max_tokens": {
        "label": "最大输出Token",
        "type": "int",
        "help": "生成的最大token数量。",
        "default": 4096,
        "min": 1,
        "max": 128000,
        "step": 256,
    },
}
